# Generated by Django 5.1.6 on 2025-02-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_quantity_product_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryprediction',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
    ]
