# Generated by Django 5.1.6 on 2025-02-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIStockForecast',
        ),
        migrations.DeleteModel(
            name='HistoricalStock',
        ),
    ]
